[package]
name = "esp_sandbox"
version = "0.1.0"
authors = ["Scott Dalgliesh <scott.t.dalgliesh@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
embedded-hal = "1.0.0"
embedded-hal-async = { version = "1.0.0" }
hal = { package = "esp32c3-hal", version = "0.15.0", features = ["embassy", "embassy-time-systick", "async", "eh1"]}
riscv-rt = { package = "esp-riscv-rt", version = "0.6.1" }
esp-backtrace = { version = "0.11.0", features = ["esp32c3", "panic-handler", "exception-handler", "println"] }
esp-println = { version = "0.9.0", features = ["esp32c3"] }
embassy-executor = { version = "0.5.0", features = ["nightly", "integrated-timers", "arch-riscv32", "executor-thread"] }
embassy-sync = { version = "0.5.0" }
embassy-time = { version = "0.3.0"}
epd-waveshare = "0.5.0"
embedded-graphics = "0.8.1"
embedded-hal-bus = "0.1.0"

[patch.crates-io]
epd-waveshare = { git = "https://github.com/scottdalgliesh/epd-waveshare.git"}

[profile.dev]
opt-level = 1

[profile.release]
debug = true
