[package]
name = "esp_sandbox"
version = "0.1.0"
authors = ["Scott Dalgliesh <scott.t.dalgliesh@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
embedded-hal-async = { version = "0.2.0-alpha.1" }
hal = { package = "esp32c3-hal", version = "0.9.0", features = [
  "embassy",
  "embassy-time",
  "embassy-time-systick",
  "embedded-hal-async",
  "async",
] }
riscv-rt = { package = "esp-riscv-rt", version = "0.3.0" }
esp-backtrace = { version = "0.7.0", features = ["esp32c3", "panic-handler", "exception-handler", "print-uart"] }
esp-println = { version = "0.5.0", features = ["esp32c3"] }
embassy-executor = { version = "0.2.0", features = ["nightly", "integrated-timers", "arch-riscv32", "executor-thread"] }
embassy-sync = { version = "0.2.0" }
embassy-time = { version = "0.1.1", features = ["nightly"] }


[patch.crates-io]
embassy-sync = { git = "https://github.com/embassy-rs/embassy" }


[profile.dev]
opt-level = 1

[profile.release]
debug = true
